https://www.tidymodels.org/start/models/
```{r setup, include=FALSE}
library(tidymodels)
library(readr)
library(broom.mixed)
library(dotwhisker)
```

Use sea urchins data

```{r cars}
urchins <- 
    read_csv("https://tidymodels.org/start/models/urchins.csv") %>%
    setNames(c("food_regime", "initial_volume", "width")) %>%
    mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))
    
urchins
```

As a first step in modeling, it's always a good idea to plot the data
```{r}
ggplot(urchins, 
       aes(x = initial_volume,
           y = width,
           group = food_regime,
           col = food_regime)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE) +
    scale_color_viridis_d(option = "plasma", end = .7)
```
```{r}
# create linear model
lm_mod <- linear_reg() %>% set_engine("lm")

# fit data
lm_fit <- lm_mod %>%
    fit(width ~ initial_volume * food_regime, data = urchins)
lm_fit
```
```{r}
tidy(lm_fit)
```
```{r}
tidy(lm_fit) %>%
    dwplot(dot_args = list(size = 2, color = "black"),
           whisker_args = list(color = "black"),
           vline = geom_vline(xintercept = 0, colour = "grey50", linetype = 2))
```

Use a model to predict
```{r}
new_points <- expand.grid(initial_volume = 20, 
                          food_regime = c("Initial", "Low", "High"))
new_points
#>   initial_volume food_regime
#> 1             20     Initial
#> 2             20         Low
#> 3             20        High

```

```{r}

mean_pred <- predict(lm_fit, new_data = new_points)
mean_pred
```
```{r}
conf_int_pred <- predict(lm_fit, 
                         new_data = new_points, 
                         type = "conf_int")
conf_int_pred
#> # A tibble: 3 x 2
#>   .pred_lower .pred_upper
#>         <dbl>       <dbl>
#> 1      0.0555      0.0729
#> 2      0.0499      0.0678
#> 3      0.0870      0.105

# Now combine: 
plot_data <- 
  new_points %>% 
  bind_cols(mean_pred) %>% 
  bind_cols(conf_int_pred)

# and plot:
ggplot(plot_data, aes(x = food_regime)) + 
  geom_point(aes(y = .pred)) + 
  geom_errorbar(aes(ymin = .pred_lower, 
                    ymax = .pred_upper),
                width = .2) + 
  labs(y = "urchin size")
```
Model with different engine: Bayesian analysis
```{r}
# set prior distribution
prior_dist <- rstanarm::student_t(df = 1)
set.seed(123)

# make the parsnip model
bayes_mod <- 
    linear_reg() %>%
    set_engine("stan",
               prior_intercept = prior_dist,
               prior = prior_dist)

# train model
bayes_fit <- 
    bayes_mod %>%
    fit(width ~ initial_volume * food_regime, data = urchins)

print(bayes_fit, digits=5)

```
```{r}
tidy(bayes_fit, conf.int = TRUE)
```
```{r}
bayes_plot_data <- 
    new_points %>%
    bind_cols(predict(bayes_fit, new_data = new_points)) %>%
    bind_cols(predict(bayes_fit, new_data = new_points, type = "conf_int"))

ggplot(bayes_plot_data, aes(x = food_regime)) +
    geom_point(aes(y = .pred)) + 
    geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), width = .2) +
    labs(y = "urchin size") +
    ggtitle("Bayesian model with t(1) prior distribution")
```


